### ISSUE TITLE
GitHub Updater branch

### ISSUE THREAD

**Issue by afragen** [michaelbroper/link-privacy#2]
You should refer your users to the `master` branch, not `develop`
https://github.com/michaelbroper/link-privacy/blob/master/index.php#L39

You might consider using https://github.com/thomasgriffin/TGM-Plugin-Activation

**Comment by michaelbroper** [comment]
Hey @afragen - can you take a look at my most recent update? It's not going out. It is yellowed like there is an update, but I can't make it update, if that makes sense. 
![banners_and_alerts_and_plugins_ _seo_revolution_ _wordpress](https://cloud.githubusercontent.com/assets/5083607/6220691/71d8d64a-b607-11e4-8bd5-b4be84982eda.jpg)

**Comment by michaelbroper** [comment]
@afragen Nevermind, Works now.

**Comment by afragen** [comment]
Excellent.
